//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public int PARAMETER_ID { get; set; }
        public string MAJOR_CODE { get; set; }
        public string MINOR_CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string C_BY { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string E_BY { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public string STATUS { get; set; }
        public string CONDITION1 { get; set; }
        public string CONDITION2 { get; set; }
    }
}
