//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSSYSTEMEntities : DbContext
    {
        public POSSYSTEMEntities()
            : base("name=POSSYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<DAPARTMENT> DAPARTMENT { get; set; }
        public virtual DbSet<INV_PRODUCTS> INV_PRODUCTS { get; set; }
        public virtual DbSet<LOGIN_ACCESS> LOGIN_ACCESS { get; set; }
        public virtual DbSet<MASTER_ROLE> MASTER_ROLE { get; set; }
        public virtual DbSet<MASTER_RUNNING> MASTER_RUNNING { get; set; }
        public virtual DbSet<MASTER_USER> MASTER_USER { get; set; }
        public virtual DbSet<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        public virtual DbSet<PARAMETER> PARAMETER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<SELLITEMS> SELLITEMS { get; set; }
    }
}
