//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.INV_PRODUCTS = new HashSet<INV_PRODUCTS>();
            this.PRODUCTS_SELL = new HashSet<PRODUCTS_SELL>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<decimal> COSTPRICE { get; set; }
        public Nullable<decimal> SELLPRICE { get; set; }
        public string PICTURE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string PRODUCT_TYPE_ID { get; set; }
        public string PRODUCT_SIZE_ID { get; set; }
        public string C_BY { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string E_BY { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string STATUS { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> RETAILPRICE { get; set; }
        public Nullable<decimal> WHOLESALEPRICE { get; set; }
        public Nullable<decimal> AVGCOST { get; set; }
        public Nullable<decimal> WHOLESALEPROFIT { get; set; }
        public Nullable<decimal> RETAILPROFIT { get; set; }
        public Nullable<int> QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> AVG_PACK { get; set; }
        public Nullable<decimal> AVG_ITEM { get; set; }
        public Nullable<decimal> WHOLESALEPRICE_ITEM { get; set; }
        public Nullable<decimal> BOXPRICE { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTS> INV_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTS_SELL> PRODUCTS_SELL { get; set; }
    }
}
