//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS_SELL
    {
        public int PRODUCT_SELL_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> INV_ID { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string C_BY { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string E_BY { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> PROFIT { get; set; }
        public string REMARK { get; set; }
        public string BARCODE { get; set; }
        public string PRODUCT_CODE { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
