//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELL_MANUAL
    {
        public int ID { get; set; }
        public string IV_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string C_BY { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string E_BY { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public string SE_NO { get; set; }
    }
}
